### ISSUE TITLE
Call to action: remove "width" attribute

### ISSUE THREAD

**Issue by mattsharkey** [web-illinois/toolkit#268]
The "width" attribute should be deprecated. You should be able to resize the component via CSS, like this:

````css
il-call-to-action {
   width: 400px;
}
````
